name: invest_ia
description: A new Flutter project for investment AI

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.7.0 <4.0.0"

dependencies:
  async: ^2.13.0
  fake_async: ^1.3.3
  material_color_utilities: ^0.11.1  # Compatible avec votre version de Flutter
  vector_math: 2.1.4
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter
  http: ^1.3.0
  audioplayers: ^6.4.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0  # Version stable compatible avec Flutter 3.29.1


flutter:
  uses-material-design: true
